### ISSUE TITLE
decrease .ico image size

### ISSUE THREAD

**Issue by snagglewest** [puavo-org/externalportal#1]
First, let me say I really like this idea!  It's a mice addition to the home page.

I know you're in the early stages but if you could maybe reduce the size of the icons, or better yet, make them adjustable, it would really help.  When the icons get enlarged they get pixelated and look bad.  A perfect solution would be if the external site addon would allows icons bigger than 32x32 icons but in the interim just adjusting them would be a big improvement.
Thanks!

**Comment by Mazhoon** [comment]
Thank you for your suggestion!
I actually never realized there's a 32x32 size limit for external sites icons, as I've only used svg icons myself. 

I'll add an option to limit icon size to 32x32 in an upcoming version I'll release probably this week.

**Comment by Mazhoon** [comment]
Implemented in 1.1.0, now available: https://github.com/puavo-org/externalportal/releases/tag/v1.1.0
I tried some values - limiting to 32x32 would make the icons really small, and cause some problems with title layouting too, so I went with a bit larger size. Option to enable available on settings page - hope you like it!

**Comment by snagglewest** [comment]
Thank you for such a quick fix, it works perfect!
