### ISSUE TITLE
Add support for Nextcloud 29

### ISSUE THREAD

**Issue by Kapujino** [puavo-org/externalportal#5]
Currently the app supports up to Nextcloud 27.
Please add support for Nextcloud 29.

edit: Nextcloud 29 release, request adjusted.

**Comment by Mazhoon** [comment]
Thank you, this is a very valid issue, but unfortunately due to various reasons, next release will have to wait till early May.

**Comment by Mazhoon** [comment]
Fixed with https://github.com/puavo-org/externalportal/releases/tag/v1.3.0 - apologies for the delay, thank you for waiting
